export type Language = "English" | "Vietnamese" | "Spanish" | "Korean" | "Chinese" | "Japanese" | "Other";
export type CostType = "Free" | "Sliding Scale" | "Insurance Accepted";
export type AgeGroup = "Youth" | "Family" | "All ages";
export type ResourceType =
  | "988 Suicide & Crisis Lifeline"
  | "Orange County Health Care Agency Behavioral Health Services"
  | "CHOC WellSpaces"
  | "School counselors and school wellness centers"
  | "Teen peer support programs"
  | "Community clinics"
  | "Family support resources"
  | "Vietnamese-language mental-health resources";
export type DeliveryMode = "In-Person" | "Virtual" | "Hotline" | "Hybrid";
export type ServiceType = "Counseling centers" | "School resources" | "Crisis lines" | "Community clinics" | "Bilingual services";
export type LanguageFilter = "All languages" | Language;
export type CostFilter = "All costs" | CostType;
export type AgeGroupFilter = "All age groups" | AgeGroup;
export type ResourceTypeFilter = "All resource types" | ResourceType;
export type ServiceTypeFilter = "All service types" | ServiceType;
export type ModeFilter = "Any format" | DeliveryMode;
export type CityFilter = "All cities" | string;

export type Resource = {
  name: string;
  resourceType: ResourceType;
  category: ResourceType;
  city: string;
  address: string | null;
  description: string;
  websiteUrl: string | null;
  phone: string;
  languages: Language[];
  costTypes: CostType[];
  cost: CostType[];
  ageGroups: AgeGroup[];
  mode: DeliveryMode;
  format: DeliveryMode;
  serviceType: ServiceType;
  latitude: number | null;
  longitude: number | null;
  coordinates: { lat: number; lng: number } | null;
  locationApproximate: boolean;
  accessibility: string[];
  tags: string[];
};

export const languageOptions: LanguageFilter[] = ["All languages", "English", "Vietnamese", "Spanish", "Korean", "Chinese", "Japanese", "Other"];
export const costOptions: CostFilter[] = ["All costs", "Free", "Sliding Scale", "Insurance Accepted"];
export const ageGroupOptions: AgeGroupFilter[] = ["All age groups", "Youth", "Family", "All ages"];
export const resourceTypeOptions: ResourceTypeFilter[] = [
  "All resource types",
  "988 Suicide & Crisis Lifeline",
  "Orange County Health Care Agency Behavioral Health Services",
  "CHOC WellSpaces",
  "School counselors and school wellness centers",
  "Teen peer support programs",
  "Community clinics",
  "Family support resources",
  "Vietnamese-language mental-health resources",
];
export const modeOptions: ModeFilter[] = ["Any format", "In-Person", "Virtual", "Hotline", "Hybrid"];
export const serviceTypeOptions: ServiceTypeFilter[] = [
  "All service types",
  "Counseling centers",
  "School resources",
  "Crisis lines",
  "Community clinics",
  "Bilingual services",
];

type ResourceInput = Omit<Resource, "category" | "cost" | "format" | "latitude" | "longitude" | "address" | "locationApproximate" | "coordinates"> & {
  address?: string | null;
  coordinates?: { lat: number; lng: number } | null;
  locationApproximate?: boolean;
};

const resource = (item: ResourceInput): Resource => ({
  ...item,
  category: item.resourceType,
  cost: item.costTypes,
  format: item.mode,
  address: item.address ?? null,
  coordinates: item.coordinates ?? null,
  latitude: item.coordinates?.lat ?? null,
  longitude: item.coordinates?.lng ?? null,
  locationApproximate: item.locationApproximate ?? !item.address,
});

export const resources: Resource[] = [
  resource({
    name: "988 Suicide & Crisis Lifeline",
    resourceType: "988 Suicide & Crisis Lifeline",
    city: "Nationwide / CA-45",
    description: "Immediate 24/7 crisis support for anyone experiencing suicidal thoughts, emotional distress, or concern for someone else.",
    websiteUrl: "https://988lifeline.org/",
    phone: "988",
    languages: ["English", "Vietnamese", "Spanish", "Korean", "Chinese", "Japanese", "Other"],
    costTypes: ["Free"],
    ageGroups: ["All ages"],
    mode: "Hotline",
    serviceType: "Crisis lines",
    address: "CA-45 service area: 11222 Acacia Pkwy, Garden Grove, CA 92840",
    coordinates: { lat: 33.7757294, lng: -117.9368784 },
    locationApproximate: true,
    accessibility: ["24/7 call, text, and chat", "Interpreter access may be requested"],
    tags: ["Crisis", "Immediate support", "Confidential"],
  }),
  resource({
    name: "OC Links Behavioral Health Navigation",
    resourceType: "Orange County Health Care Agency Behavioral Health Services",
    city: "Orange County",
    description: "Free county behavioral-health navigation that connects residents to mental-health and substance-use referrals, crisis support, and programs.",
    websiteUrl: "https://www.ochealthinfo.com/OCLINKS",
    phone: "855-625-4657",
    languages: ["English", "Vietnamese", "Spanish", "Korean", "Chinese", "Japanese", "Other"],
    costTypes: ["Free"],
    ageGroups: ["Youth", "Family", "All ages"],
    mode: "Hotline",
    serviceType: "Crisis lines",
    address: "405 W 5th St., Santa Ana, CA 92701",
    coordinates: { lat: 33.7489608, lng: -117.8711732 },
    accessibility: ["24/7 phone and online chat", "County navigation line"],
    tags: ["Orange County", "Referrals", "Behavioral health"],
  }),
  resource({
    name: "OC HCA Children & Youth Behavioral Health Services",
    resourceType: "Orange County Health Care Agency Behavioral Health Services",
    city: "Orange County",
    description: "County children and youth behavioral-health services, including prevention, crisis recovery, outpatient support, and specialty programs.",
    websiteUrl: "https://www.ochealthinfo.com/services-programs/mental-health-crisis-recovery/children-youth-services",
    phone: "855-625-4657",
    languages: ["English", "Vietnamese", "Spanish", "Korean", "Chinese", "Japanese", "Other"],
    costTypes: ["Free", "Insurance Accepted"],
    ageGroups: ["Youth", "Family"],
    mode: "Hybrid",
    serviceType: "Counseling centers",
    address: "405 W 5th St., Santa Ana, CA 92701",
    coordinates: { lat: 33.7489608, lng: -117.8711732 },
    accessibility: ["Countywide youth services", "Call OC Links for navigation"],
    tags: ["Youth", "County services", "Prevention"],
  }),
  resource({
    name: "Be Well OC Orange Campus",
    resourceType: "Orange County Health Care Agency Behavioral Health Services",
    city: "Orange",
    description: "Orange County mental-health and substance-use support campus with system navigation for residents seeking help.",
    websiteUrl: "https://bewelloc.org/be-well-orange-campus/",
    phone: "949-749-2500",
    languages: ["English", "Vietnamese", "Spanish", "Korean", "Chinese", "Japanese", "Other"],
    costTypes: ["Free", "Insurance Accepted"],
    ageGroups: ["All ages"],
    mode: "Hybrid",
    serviceType: "Counseling centers",
    address: "1201 W La Veta Ave, Orange, CA 92868",
    coordinates: { lat: 33.7809052, lng: -117.8660899 },
    accessibility: ["Non-crisis navigation line", "OC Links for crisis or substance-use support"],
    tags: ["Navigation", "Mental health", "Substance use"],
  }),
  resource({
    name: "NAMI Orange County WarmLine",
    resourceType: "Teen peer support programs",
    city: "Fountain Valley",
    description: "Free confidential emotional support and resource connection for Orange County residents by phone, text, or chat.",
    websiteUrl: "https://www.namioc.org/oc-warmline",
    phone: "714-991-6412",
    languages: ["English", "Spanish", "Korean", "Chinese", "Other"],
    costTypes: ["Free"],
    ageGroups: ["Youth", "Family", "All ages"],
    mode: "Hotline",
    serviceType: "Crisis lines",
    address: "16480 S Harbor Blvd, Suite 101, Fountain Valley, CA 92708",
    coordinates: { lat: 33.7209315, lng: -117.9202835 },
    accessibility: ["Call, text, and chat options", "Orange County residents"],
    tags: ["Warmline", "Peer support", "Emotional support"],
  }),
  resource({
    name: "NAMI Orange County Teens & Young Adults",
    resourceType: "Teen peer support programs",
    city: "Fountain Valley",
    description: "Teen and young-adult mental-health resources, peer stories, and support pathways from NAMI Orange County.",
    websiteUrl: "https://www.namioc.org/teens-young-adults",
    phone: "714-544-8488",
    languages: ["English", "Spanish", "Other"],
    costTypes: ["Free"],
    ageGroups: ["Youth"],
    mode: "Hybrid",
    serviceType: "Counseling centers",
    address: "16480 S Harbor Blvd, Suite 101, Fountain Valley, CA 92708",
    coordinates: { lat: 33.7209315, lng: -117.9202835 },
    accessibility: ["Youth-focused resources", "Peer and family education"],
    tags: ["Peer support", "Young adults", "Education"],
  }),
  resource({
    name: "NAMI Orange County Family Support Groups",
    resourceType: "Family support resources",
    city: "Fountain Valley",
    description: "Peer-led family support groups and education for caregivers and loved ones supporting someone with a mental-health condition.",
    websiteUrl: "https://www.namioc.org/support-groups",
    phone: "714-544-8488",
    languages: ["English", "Spanish", "Other"],
    costTypes: ["Free"],
    ageGroups: ["Family"],
    mode: "Hybrid",
    serviceType: "Counseling centers",
    address: "16480 S Harbor Blvd, Suite 101, Fountain Valley, CA 92708",
    coordinates: { lat: 33.7209315, lng: -117.9202835 },
    accessibility: ["Caregiver-friendly", "Group support options"],
    tags: ["Caregivers", "Family education", "Support groups"],
  }),
  resource({
    name: "Western Youth Services Mental Health Clinics",
    resourceType: "Community clinics",
    city: "Santa Ana",
    description: "Outpatient mental-health services for Orange County children and youth, including Medi-Cal eligible clients under 21.",
    websiteUrl: "https://www.westernyouthservices.org/mental-health-clinics/",
    phone: "888-312-0406",
    languages: ["English", "Spanish", "Other"],
    costTypes: ["Free", "Insurance Accepted"],
    ageGroups: ["Youth", "Family"],
    mode: "Hybrid",
    serviceType: "Counseling centers",
    address: "200 W Santa Ana Blvd, Suite 801, Santa Ana, CA 92701",
    coordinates: { lat: 33.749726, lng: -117.8673014 },
    accessibility: ["Clinic-based and school-based services", "Countywide locations"],
    tags: ["Youth therapy", "Medi-Cal", "Trauma-informed"],
  }),
  resource({
    name: "Waymakers Youth Shelters",
    resourceType: "Teen peer support programs",
    city: "Orange County",
    description: "Short-term shelter and crisis intervention for runaway, homeless, abused, and at-risk youth ages 11-17.",
    websiteUrl: "https://waymakersoc.org/sheltering-children",
    phone: "714-842-6600",
    languages: ["English", "Spanish", "Other"],
    costTypes: ["Free"],
    ageGroups: ["Youth", "Family"],
    mode: "In-Person",
    serviceType: "Counseling centers",
    address: "440 Exchange, Suite 250, Irvine, CA 92602",
    coordinates: { lat: 33.7136066, lng: -117.784725 },
    accessibility: ["24-hour youth shelter hotline", "Youth and family crisis intervention"],
    tags: ["Shelter", "At-risk youth", "Family conflict"],
  }),
  resource({
    name: "The Priority Center",
    resourceType: "Family support resources",
    city: "Santa Ana",
    description: "Early intervention, crisis support, mental-health services, and family advocacy for Orange County children and families.",
    websiteUrl: "https://theprioritycenter.org/programs/",
    phone: "714-543-4333",
    languages: ["English", "Spanish", "Other"],
    costTypes: ["Free", "Sliding Scale"],
    ageGroups: ["Youth", "Family", "All ages"],
    mode: "Hybrid",
    serviceType: "Counseling centers",
    address: "1932 E Deere Ave, Suite 240, Santa Ana, CA 92705",
    coordinates: { lat: 33.7041763, lng: -117.8485088 },
    accessibility: ["Family-centered programs", "Crisis and early-intervention support"],
    tags: ["Family support", "Early intervention", "Crisis support"],
  }),
  resource({
    name: "CHOC Pediatric Mental Health Services",
    resourceType: "CHOC WellSpaces",
    city: "Orange",
    description: "Pediatric mental-health resources, education, and behavioral-health information for children, teens, parents, and caregivers.",
    websiteUrl: "https://choc.org/mental-health/",
    phone: "714-997-3000",
    languages: ["English", "Spanish", "Other"],
    costTypes: ["Free", "Insurance Accepted"],
    ageGroups: ["Youth", "Family"],
    mode: "Hybrid",
    serviceType: "Counseling centers",
    address: "1201 W La Veta Ave, Orange, CA 92868",
    coordinates: { lat: 33.7809052, lng: -117.8660899 },
    accessibility: ["Pediatric focus", "Education resources for families"],
    tags: ["Pediatric", "Mental health education", "Parent support"],
  }),
  resource({
    name: "CHOC WellSpaces",
    resourceType: "CHOC WellSpaces",
    city: "Orange County schools",
    description: "Youth-centered wellness spaces and school-linked supports designed to reduce stress and connect students with trusted adults.",
    websiteUrl: "https://choc.org/population-health/wellspaces/",
    phone: "714-997-3000",
    languages: ["English", "Spanish", "Other"],
    costTypes: ["Free"],
    ageGroups: ["Youth"],
    mode: "In-Person",
    serviceType: "School resources",
    address: "1201 W La Veta Ave, Orange, CA 92868",
    coordinates: { lat: 33.7809052, lng: -117.8660899 },
    accessibility: ["School-based setting", "Youth-friendly environment"],
    tags: ["CHOC", "Wellness", "School-based"],
  }),
  resource({
    name: "OCAPICA Behavioral Health Services",
    resourceType: "Vietnamese-language mental-health resources",
    city: "Garden Grove",
    description: "Culturally responsive behavioral-health services including therapy, case management, wellness workshops, referrals, and peer support.",
    websiteUrl: "https://www.ocapica.org/bhs.html",
    phone: "714-461-3687",
    languages: ["Vietnamese", "English", "Spanish", "Korean", "Chinese", "Other"],
    costTypes: ["Free", "Sliding Scale"],
    ageGroups: ["Youth", "Family", "All ages"],
    mode: "Hybrid",
    serviceType: "Bilingual services",
    address: "12966 Euclid St., Suite 495, Garden Grove, CA 92840",
    coordinates: { lat: 33.7746619, lng: -117.9378198 },
    accessibility: ["AAPI-focused services", "Vietnamese and multilingual support"],
    tags: ["Vietnamese", "AAPI", "Case management"],
  }),
  resource({
    name: "Southland Integrated Services Behavioral Health",
    resourceType: "Vietnamese-language mental-health resources",
    city: "Garden Grove",
    description: "Culturally responsive behavioral-health care for Vietnamese Americans and other Orange County communities, including therapy and medication support.",
    websiteUrl: "https://www.southlandintegrated.org/bh.asp",
    phone: "714-620-7000",
    languages: ["Vietnamese", "English", "Spanish", "Chinese", "Other"],
    costTypes: ["Sliding Scale", "Insurance Accepted"],
    ageGroups: ["Youth", "Family", "All ages"],
    mode: "Hybrid",
    serviceType: "Bilingual services",
    address: "9862 Chapman Ave., Garden Grove, CA 92841",
    coordinates: { lat: 33.7887638, lng: -117.9606498 },
    accessibility: ["FQHC integrated care", "Vietnamese community roots"],
    tags: ["Vietnamese", "FQHC", "Therapy"],
  }),
  resource({
    name: "Families Together OC Garden Grove Health Center",
    resourceType: "Community clinics",
    city: "Garden Grove",
    description: "Community clinic in Garden Grove offering medical care and mental-health services such as individual counseling.",
    websiteUrl: "https://familiestogetheroc.org/locations/garden-grove",
    phone: "800-597-7977",
    languages: ["English", "Vietnamese", "Spanish", "Korean", "Chinese", "Japanese", "Other"],
    costTypes: ["Sliding Scale", "Insurance Accepted"],
    ageGroups: ["Youth", "Family", "All ages"],
    mode: "Hybrid",
    serviceType: "Community clinics",
    address: "9918 Katella Ave., Garden Grove, CA 92804",
    coordinates: { lat: 33.8029442, lng: -117.9600042 },
    accessibility: ["Community clinic", "Ask about interpretation"],
    tags: ["Clinic", "Counseling", "Garden Grove"],
  }),
  resource({
    name: "Serve the People Behavioral Health",
    resourceType: "Community clinics",
    city: "Santa Ana",
    description: "Affordable behavioral-health care and counseling services from an integrated community health center in Santa Ana.",
    websiteUrl: "https://www.servethepeople.org/behavioral-health",
    phone: "714-352-2911",
    languages: ["English", "Vietnamese", "Spanish", "Korean", "Chinese", "Japanese", "Other"],
    costTypes: ["Sliding Scale", "Insurance Accepted"],
    ageGroups: ["Youth", "Family", "All ages"],
    mode: "Hybrid",
    serviceType: "Community clinics",
    address: "1206 E 17th St., Santa Ana, CA 92701",
    coordinates: { lat: 33.7601068, lng: -117.8538185 },
    accessibility: ["Affordable community clinic", "Integrated medical and behavioral health"],
    tags: ["Santa Ana", "Counseling", "Clinic"],
  }),
  resource({
    name: "AltaMed Behavioral Health Services",
    resourceType: "Community clinics",
    city: "Orange County",
    description: "Short-term therapy and behavioral-health linkage through AltaMed for patients and families needing mental-health support.",
    websiteUrl: "https://www.altamed.org/behavioral-health-services",
    phone: "855-425-1777",
    languages: ["English", "Vietnamese", "Spanish", "Korean", "Chinese", "Japanese", "Other"],
    costTypes: ["Insurance Accepted", "Sliding Scale"],
    ageGroups: ["Youth", "Family", "All ages"],
    mode: "Hybrid",
    serviceType: "Community clinics",
    address: "2720 S Bristol St., Suite 110, Santa Ana, CA 92704",
    coordinates: { lat: 33.7109422, lng: -117.8855143 },
    accessibility: ["Community health network", "Bilingual Spanish support"],
    tags: ["Behavioral health", "Clinic", "Spanish"],
  }),
  resource({
    name: "Latino Health Access",
    resourceType: "Family support resources",
    city: "Santa Ana",
    description: "Community-based health education, services, and advocacy with culturally and linguistically appropriate programs for Orange County families.",
    websiteUrl: "https://latinohealthaccess.org/programs/",
    phone: "714-542-7792",
    languages: ["English", "Spanish", "Korean", "Chinese", "Japanese"],
    costTypes: ["Free", "Sliding Scale"],
    ageGroups: ["Youth", "Family", "All ages"],
    mode: "Hybrid",
    serviceType: "Bilingual services",
    address: "450 W 4th St., Santa Ana, CA 92701",
    coordinates: { lat: 33.7478861, lng: -117.8713371 },
    accessibility: ["Promotores/community model", "Spanish-language support"],
    tags: ["Family support", "Spanish", "Community health"],
  }),
  resource({
    name: "LGBTQ Center OC Therapy",
    resourceType: "Teen peer support programs",
    city: "Santa Ana",
    description: "LGBTQ-affirming therapy, groups, and mental-health support for Orange County community members.",
    websiteUrl: "https://www.lgbtqcenteroc.org/services/therapy/",
    phone: "714-953-5428",
    languages: ["English", "Spanish", "Other"],
    costTypes: ["Sliding Scale"],
    ageGroups: ["Youth", "Family", "All ages"],
    mode: "Hybrid",
    serviceType: "Counseling centers",
    address: "1605 N Spurgeon St., Santa Ana, CA 92701",
    coordinates: { lat: 33.7593163, lng: -117.864882 },
    accessibility: ["LGBTQ-affirming care", "Sliding-scale groups"],
    tags: ["LGBTQ", "Therapy", "Santa Ana"],
  }),
  resource({
    name: "California Youth Crisis Line",
    resourceType: "Teen peer support programs",
    city: "California / CA-45",
    description: "24/7 statewide crisis support for youth ages 12-24 and families in crisis, with counseling and local resource referrals.",
    websiteUrl: "https://calyouth.org/cycl/",
    phone: "800-843-5200",
    languages: ["English", "Spanish", "Other"],
    costTypes: ["Free"],
    ageGroups: ["Youth", "Family"],
    mode: "Hotline",
    serviceType: "Crisis lines",
    address: "CA-45 service area: 11222 Acacia Pkwy, Garden Grove, CA 92840",
    coordinates: { lat: 33.7757294, lng: -117.9368784 },
    locationApproximate: true,
    accessibility: ["24/7 statewide youth line", "Resource referrals"],
    tags: ["Youth crisis", "Hotline", "California"],
  }),
  resource({
    name: "Teen Line by Didi Hirsch",
    resourceType: "Teen peer support programs",
    city: "California / CA-45",
    description: "Peer-to-peer teen support line where trained teens help other teens talk through stress, relationships, anxiety, and crisis concerns.",
    websiteUrl: "https://didihirsch.org/teenline/",
    phone: "800-852-8336",
    languages: ["English", "Spanish", "Other"],
    costTypes: ["Free"],
    ageGroups: ["Youth"],
    mode: "Hotline",
    serviceType: "Crisis lines",
    address: "CA-45 service area: 11222 Acacia Pkwy, Garden Grove, CA 92840",
    coordinates: { lat: 33.7757294, lng: -117.9368784 },
    locationApproximate: true,
    accessibility: ["Teen peer support", "Evening hotline"],
    tags: ["Peer support", "Teen hotline", "Didi Hirsch"],
  }),
  resource({
    name: "The Trevor Project",
    resourceType: "Teen peer support programs",
    city: "Nationwide / CA-45",
    description: "24/7 crisis support and suicide prevention services for LGBTQ+ young people by phone, chat, and text.",
    websiteUrl: "https://www.thetrevorproject.org/",
    phone: "866-488-7386",
    languages: ["English", "Spanish", "Other"],
    costTypes: ["Free"],
    ageGroups: ["Youth"],
    mode: "Hotline",
    serviceType: "Crisis lines",
    address: "CA-45 service area: 11222 Acacia Pkwy, Garden Grove, CA 92840",
    coordinates: { lat: 33.7757294, lng: -117.9368784 },
    locationApproximate: true,
    accessibility: ["24/7 LGBTQ+ youth crisis support", "Phone, chat, and text"],
    tags: ["LGBTQ", "Crisis", "Youth"],
  }),
  resource({
    name: "Crisis Text Line",
    resourceType: "988 Suicide & Crisis Lifeline",
    city: "Nationwide / CA-45",
    description: "Free 24/7 confidential text-based crisis support with trained volunteer Crisis Counselors.",
    websiteUrl: "https://www.crisistextline.org/",
    phone: "Text HOME to 741741",
    languages: ["English", "Spanish"],
    costTypes: ["Free"],
    ageGroups: ["Youth", "Family", "All ages"],
    mode: "Hotline",
    serviceType: "Crisis lines",
    address: "CA-45 service area: 11222 Acacia Pkwy, Garden Grove, CA 92840",
    coordinates: { lat: 33.7757294, lng: -117.9368784 },
    locationApproximate: true,
    accessibility: ["Text-based support", "24/7 confidential service"],
    tags: ["Text", "Crisis", "Confidential"],
  }),
  resource({
    name: "GGUSD Mental Health Resources",
    resourceType: "School counselors and school wellness centers",
    city: "Garden Grove",
    description: "Garden Grove Unified mental-health resource page with crisis numbers, district supports, and community resource links for students and families.",
    websiteUrl: "https://ggusd.us/resources/wellness-resources/mental-health-resources",
    phone: "714-663-6000",
    languages: ["English", "Vietnamese", "Spanish", "Other"],
    costTypes: ["Free"],
    ageGroups: ["Youth", "Family"],
    mode: "Hybrid",
    serviceType: "School resources",
    address: "10331 Stanford Ave., Garden Grove, CA 92840",
    coordinates: { lat: 33.7777903, lng: -117.9525321 },
    accessibility: ["School district resources", "Ask school site for interpretation"],
    tags: ["School", "Garden Grove", "Wellness"],
  }),
  resource({
    name: "Westminster High School THE WELL",
    resourceType: "School counselors and school wellness centers",
    city: "Westminster",
    description: "On-campus wellness center offering free student mental-health services, family support, case management, and referrals during school hours.",
    websiteUrl: "https://www.whslions.net/apps/pages/index.jsp?type=d&uREC_ID=4352301",
    phone: "714-893-1381",
    languages: ["English", "Vietnamese", "Spanish", "Other"],
    costTypes: ["Free"],
    ageGroups: ["Youth", "Family"],
    mode: "In-Person",
    serviceType: "School resources",
    address: "14325 Goldenwest St., Westminster, CA 92683",
    coordinates: { lat: 33.7537524, lng: -118.0110522 },
    accessibility: ["For Westminster High students", "On-campus support"],
    tags: ["School wellness", "Westminster", "Student support"],
  }),
  resource({
    name: "HBUHSD Wellness Resources",
    resourceType: "School counselors and school wellness centers",
    city: "Huntington Beach / Fountain Valley / Westminster",
    description: "Huntington Beach Union High School District wellness resources and student mental-health supports, including teletherapy information.",
    websiteUrl: "https://www.hbuhsd.edu/apps/pages/wellness",
    phone: "714-903-7000",
    languages: ["English", "Spanish", "Other"],
    costTypes: ["Free"],
    ageGroups: ["Youth", "Family"],
    mode: "Hybrid",
    serviceType: "School resources",
    address: "5832 Bolsa Ave., Huntington Beach, CA 92649",
    coordinates: { lat: 33.74391, lng: -118.0271795 },
    accessibility: ["District student resources", "Virtual support information"],
    tags: ["School", "Teletherapy", "Wellness"],
  }),
  resource({
    name: "Fountain Valley School District Mental Health & Wellness Resources",
    resourceType: "School counselors and school wellness centers",
    city: "Fountain Valley",
    description: "District mental-health and wellness resource page with crisis contacts, community partners, and family support links.",
    websiteUrl: "https://www.fvsd.us/apps/pages/MentalHealthAndWellnessResources",
    phone: "714-843-3200",
    languages: ["English", "Spanish", "Other"],
    costTypes: ["Free"],
    ageGroups: ["Youth", "Family"],
    mode: "Hybrid",
    serviceType: "School resources",
    address: "10055 Slater Ave., Fountain Valley, CA 92708",
    coordinates: { lat: 33.7096411, lng: -117.9533425 },
    accessibility: ["District resource page", "Family and student supports"],
    tags: ["School", "Fountain Valley", "Wellness"],
  }),
  resource({
    name: "Westminster School District Family/Community Resources",
    resourceType: "School counselors and school wellness centers",
    city: "Westminster",
    description: "Westminster School District family and community resource hub with mental-health, wellness, medical, and support information.",
    websiteUrl: "https://www.wsdk8.us/parentstudent/familycommunity-resources",
    phone: "714-894-7311",
    languages: ["English", "Vietnamese", "Spanish", "Other"],
    costTypes: ["Free"],
    ageGroups: ["Youth", "Family"],
    mode: "Hybrid",
    serviceType: "School resources",
    address: "14121 Cedarwood St., Westminster, CA 92683",
    coordinates: { lat: 33.757051, lng: -117.9941812 },
    accessibility: ["School district family resources", "Community support links"],
    tags: ["School", "Westminster", "Family resources"],
  }),
  resource({
    name: "OC HCA Children and Youth Services Outpatient Clinics",
    resourceType: "Orange County Health Care Agency Behavioral Health Services",
    city: "Orange County",
    description: "County outpatient clinics providing assessment, therapy, medication monitoring, crisis intervention, and collateral services for children and adolescents.",
    websiteUrl: "https://www.ochealthinfo.com/services-programs/mental-health-crisis-recovery/children-youth-services/outpatient-services",
    phone: "855-625-4657",
    languages: ["English", "Vietnamese", "Spanish", "Korean", "Chinese", "Japanese", "Other"],
    costTypes: ["Free", "Insurance Accepted"],
    ageGroups: ["Youth", "Family"],
    mode: "Hybrid",
    serviceType: "Counseling centers",
    address: "405 W 5th St., Santa Ana, CA 92701",
    coordinates: { lat: 33.7489608, lng: -117.8711732 },
    locationApproximate: true,
    accessibility: ["Countywide outpatient youth behavioral-health services", "Call OC Links for navigation"],
    tags: ["Youth therapy", "County clinics", "Medication support"],
  }),
  resource({
    name: "OC HCA Children and Youth Crisis Assessment Team",
    resourceType: "Orange County Health Care Agency Behavioral Health Services",
    city: "Orange County",
    description: "County crisis assessment support for minors physically located in Orange County who need urgent behavioral-health evaluation and linkage.",
    websiteUrl: "https://www.ochealthinfo.com/about-hca/behavioral-health-services/more-mhrs/crisis-services",
    phone: "866-830-6011",
    languages: ["English", "Vietnamese", "Spanish", "Korean", "Chinese", "Japanese", "Other"],
    costTypes: ["Free"],
    ageGroups: ["Youth", "Family"],
    mode: "Hotline",
    serviceType: "Crisis lines",
    address: "405 W 5th St., Santa Ana, CA 92701",
    coordinates: { lat: 33.7489608, lng: -117.8711732 },
    locationApproximate: true,
    accessibility: ["24/7 county crisis response for minors", "Use 988 or 911 for immediate life-threatening danger"],
    tags: ["Youth crisis", "County crisis", "Assessment"],
  }),
  resource({
    name: "OC HCA Program for Assertive Community Treatment",
    resourceType: "Orange County Health Care Agency Behavioral Health Services",
    city: "Orange County",
    description: "Intensive county-connected support for Orange County youth ages 14-21 with serious behavioral-health needs and eligible referrals.",
    websiteUrl: "https://www.ochealthinfo.com/services-programs/mental-health-crisis-recovery/children-youth-services/outpatient-services/full-0",
    phone: "855-625-4657",
    languages: ["English", "Spanish", "Other"],
    costTypes: ["Free", "Insurance Accepted"],
    ageGroups: ["Youth", "Family"],
    mode: "Hybrid",
    serviceType: "Counseling centers",
    address: "405 W 5th St., Santa Ana, CA 92701",
    coordinates: { lat: 33.7489608, lng: -117.8711732 },
    locationApproximate: true,
    accessibility: ["Referral-based county youth program", "Interpretation available upon request"],
    tags: ["TAY", "Intensive support", "County services"],
  }),
  resource({
    name: "OC HCA Alcohol and Substance Use Services",
    resourceType: "Orange County Health Care Agency Behavioral Health Services",
    city: "Orange County",
    description: "County alcohol and substance-use treatment system with outpatient and residential options to reduce or eliminate alcohol and drug misuse.",
    websiteUrl: "https://www.ochealthinfo.com/services-programs/mental-health-crisis-recovery/alcohol-substance-use-services",
    phone: "855-625-4657",
    languages: ["English", "Vietnamese", "Spanish", "Korean", "Chinese", "Japanese", "Other"],
    costTypes: ["Free", "Insurance Accepted"],
    ageGroups: ["Youth", "Family", "All ages"],
    mode: "Hybrid",
    serviceType: "Counseling centers",
    address: "405 W 5th St., Santa Ana, CA 92701",
    coordinates: { lat: 33.7489608, lng: -117.8711732 },
    locationApproximate: true,
    accessibility: ["County substance-use navigation", "Call OC Links for referrals"],
    tags: ["Substance use", "Prevention", "Treatment navigation"],
  }),
  resource({
    name: "OC HCA West Region Behavioral Health Services",
    resourceType: "Orange County Health Care Agency Behavioral Health Services",
    city: "Westminster",
    address: "14140 Beach Blvd., Suite 223, Westminster, CA 92683",
    description: "County west-region outpatient behavioral-health services serving Cypress, Fountain Valley, Los Alamitos, Stanton, Westminster, and nearby communities.",
    websiteUrl: "https://www.ochealthinfo.com/services-programs/mental-health-crisis-recovery/adult-18-services/outpatient-services/outpatient",
    phone: "714-896-7566",
    languages: ["English", "Spanish", "Other"],
    costTypes: ["Free", "Insurance Accepted"],
    ageGroups: ["Family", "All ages"],
    mode: "In-Person",
    serviceType: "Counseling centers",
    coordinates: { lat: 33.7571856, lng: -117.989431 },
    accessibility: ["West county outpatient access point", "Dual diagnosis services available"],
    tags: ["Westminster", "Outpatient", "County services"],
  }),
  resource({
    name: "OC HCA Pacific Asian Services",
    resourceType: "Vietnamese-language mental-health resources",
    city: "Westminster",
    address: "14140 Beach Blvd., Suite 200, Westminster, CA 92683",
    description: "County-operated Pacific Asian behavioral-health services in Westminster for culturally responsive care and support.",
    websiteUrl: "https://www.ochealthinfo.com/services-programs/mental-health-crisis-recovery/adult-18-services/outpatient-services/outpatient",
    phone: "714-896-7566",
    languages: ["Vietnamese", "English", "Spanish", "Korean", "Chinese", "Other"],
    costTypes: ["Free", "Insurance Accepted"],
    ageGroups: ["Family", "All ages"],
    mode: "In-Person",
    serviceType: "Bilingual services",
    coordinates: { lat: 33.7571856, lng: -117.989431 },
    accessibility: ["Pacific Asian service focus", "Westminster location"],
    tags: ["AAPI", "Vietnamese", "Westminster"],
  }),
  resource({
    name: "Cypress College Student Health and Wellness Center",
    resourceType: "School counselors and school wellness centers",
    city: "Cypress",
    address: "9200 Valley View Street, Cypress, CA 90630",
    description: "Student Health and Wellness Center offering mental-health counseling, crisis walk-in hours, Zoom appointments, and after-hours telemental-health appointments for students.",
    websiteUrl: "https://www.cypresscollege.edu/academics/divisions-special-programs/services/health-center/",
    phone: "714-484-7361",
    languages: ["English", "Spanish", "Other"],
    costTypes: ["Free"],
    ageGroups: ["Youth", "All ages"],
    mode: "Hybrid",
    serviceType: "School resources",
    coordinates: { lat: 33.8290008, lng: -118.0256044 },
    accessibility: ["For Cypress College students", "In-person and remote options"],
    tags: ["College", "Counseling", "Cypress"],
  }),
  resource({
    name: "Cypress College Mental Health Resources",
    resourceType: "School counselors and school wellness centers",
    city: "Cypress",
    address: "9200 Valley View Street, Cypress, CA 90630",
    description: "Cypress College resource page connecting students to mental-health counseling, crisis lines, and community support options.",
    websiteUrl: "https://www.cypresscollege.edu/academics/divisions-special-programs/services/health-center/mental-health-resources/",
    phone: "714-484-7361",
    languages: ["English", "Spanish", "Other"],
    costTypes: ["Free"],
    ageGroups: ["Youth", "All ages"],
    mode: "Hybrid",
    serviceType: "School resources",
    coordinates: { lat: 33.8290008, lng: -118.0256044 },
    accessibility: ["Student mental-health resource page", "Crisis and counseling links"],
    tags: ["College", "Mental health resources", "Cypress"],
  }),
  resource({
    name: "Fullerton Joint Union High School District Mental Health",
    resourceType: "School counselors and school wellness centers",
    city: "Fullerton",
    description: "District mental-health homepage with student and family resources, parent supports, and links for getting help through school sites.",
    websiteUrl: "https://www.fjuhsd.org/mental-health-homepage",
    phone: "714-870-2800",
    languages: ["English", "Spanish", "Korean", "Chinese", "Other"],
    costTypes: ["Free"],
    ageGroups: ["Youth", "Family"],
    mode: "Hybrid",
    serviceType: "School resources",
    address: "1051 W Bastanchury Rd, Fullerton, CA 92833",
    coordinates: { lat: 33.8886165, lng: -117.9444342 },
    locationApproximate: true,
    accessibility: ["District resource hub", "For FJUHSD students and families"],
    tags: ["School", "Fullerton", "Wellness"],
  }),
  resource({
    name: "Fullerton School District Social Emotional Services",
    resourceType: "School counselors and school wellness centers",
    city: "Fullerton",
    description: "School district social-emotional and mental-health therapy supports including groups, classroom lessons, coping strategies, and behavior regulation.",
    websiteUrl: "https://www.fullertonsd.org/departments/human-resources-homepage/student-support-services/social-emotional-services-mental-health-therapy",
    phone: "714-447-7400",
    languages: ["English", "Spanish", "Korean", "Chinese", "Other"],
    costTypes: ["Free"],
    ageGroups: ["Youth", "Family"],
    mode: "In-Person",
    serviceType: "School resources",
    address: "1401 W Valencia Dr, Fullerton, CA 92833",
    coordinates: { lat: 33.8669896, lng: -117.9511765 },
    locationApproximate: true,
    accessibility: ["School-based social-emotional supports", "Contact school site for access"],
    tags: ["Elementary", "Social emotional", "Fullerton"],
  }),
  resource({
    name: "Buena Park School District Mental Health and Wellness",
    resourceType: "School counselors and school wellness centers",
    city: "Buena Park",
    description: "District mental-health and wellness resource page connecting students, staff, and families to mental-health and substance-use providers.",
    websiteUrl: "https://www.bpsd.us/divisions/educational-services/student-and-community-services/mental-health-wellness-support-and-resources",
    phone: "714-736-4253",
    languages: ["English", "Spanish", "Korean", "Chinese", "Other"],
    costTypes: ["Free"],
    ageGroups: ["Youth", "Family"],
    mode: "Hybrid",
    serviceType: "School resources",
    address: "6885 Orangethorpe Ave., Buena Park, CA 90620",
    coordinates: { lat: 33.8593131, lng: -118.015201 },
    locationApproximate: true,
    accessibility: ["District student and family resource page", "Care coordination links"],
    tags: ["School", "Buena Park", "Wellness"],
  }),
  resource({
    name: "Buena Park High School Wellness Center",
    resourceType: "School counselors and school wellness centers",
    city: "Buena Park",
    description: "School-based wellness center and counseling office support for Buena Park High students' emotional and mental wellbeing.",
    websiteUrl: "https://www.buenaparkhs.org/wellness-center-2",
    phone: "714-992-8642",
    languages: ["English", "Spanish", "Korean", "Chinese", "Other"],
    costTypes: ["Free"],
    ageGroups: ["Youth", "Family"],
    mode: "In-Person",
    serviceType: "School resources",
    address: "8833 Academy Dr., Buena Park, CA 90621",
    coordinates: { lat: 33.862358, lng: -117.9785547 },
    locationApproximate: true,
    accessibility: ["For Buena Park High students", "Contact counseling office"],
    tags: ["High school", "Wellness center", "Buena Park"],
  }),
  resource({
    name: "Los Alamitos Unified Mental Health",
    resourceType: "School counselors and school wellness centers",
    city: "Los Alamitos",
    description: "District mental-health support page with Care Solace navigation for students, staff, and families seeking local programs and counseling.",
    websiteUrl: "https://www.losal.org/departments/mental-health",
    phone: "562-799-4700",
    languages: ["English", "Spanish", "Korean", "Chinese", "Other"],
    costTypes: ["Free"],
    ageGroups: ["Youth", "Family"],
    mode: "Hybrid",
    serviceType: "School resources",
    address: "10293 Bloomfield St., Los Alamitos, CA 90720",
    coordinates: { lat: 33.8010464, lng: -118.0632029 },
    locationApproximate: true,
    accessibility: ["For Los Alamitos USD students and families", "24/7 care navigation resource"],
    tags: ["School", "Los Alamitos", "Care Solace"],
  }),
  resource({
    name: "Los Alamitos Unified Wellness",
    resourceType: "School counselors and school wellness centers",
    city: "Los Alamitos",
    address: "10293 Bloomfield St., Los Alamitos, CA 90720",
    description: "District wellness contacts and mental-health wellness coordination for Los Alamitos Unified students and families.",
    websiteUrl: "https://www.losal.org/programs/wellness",
    phone: "562-799-4700",
    languages: ["English", "Spanish", "Korean", "Chinese", "Other"],
    costTypes: ["Free"],
    ageGroups: ["Youth", "Family"],
    mode: "Hybrid",
    serviceType: "School resources",
    coordinates: { lat: 33.8010464, lng: -118.0632029 },
    accessibility: ["District wellness contacts", "School-based support coordination"],
    tags: ["Wellness", "Los Alamitos", "School"],
  }),
  resource({
    name: "Santa Ana Unified Wellness Center",
    resourceType: "School counselors and school wellness centers",
    city: "Santa Ana",
    description: "SAUSD wellness center information connecting students and families with FACE liaisons and school-based support.",
    websiteUrl: "https://www.sausd.us/community/face/wellness-center",
    phone: "714-433-3481",
    languages: ["English", "Vietnamese", "Spanish", "Other"],
    costTypes: ["Free"],
    ageGroups: ["Youth", "Family"],
    mode: "In-Person",
    serviceType: "School resources",
    address: "1801 S. Poplar St., Santa Ana, CA 92704",
    coordinates: { lat: 33.7241708, lng: -117.8863955 },
    locationApproximate: true,
    accessibility: ["School site wellness centers", "Family and Community Engagement support"],
    tags: ["School", "Santa Ana", "Wellness"],
  }),
  resource({
    name: "Santa Ana Unified Support Services",
    resourceType: "School counselors and school wellness centers",
    city: "Santa Ana",
    address: "1801 S. Poplar St., Santa Ana, CA 92704",
    description: "SAUSD support services office with mental-health and support coordination for students and families.",
    websiteUrl: "https://www.sausd.us/departments/educational-services/support-services",
    phone: "714-433-3483",
    languages: ["English", "Vietnamese", "Spanish", "Other"],
    costTypes: ["Free"],
    ageGroups: ["Youth", "Family"],
    mode: "Hybrid",
    serviceType: "School resources",
    coordinates: { lat: 33.7241708, lng: -117.8863955 },
    accessibility: ["District mental-health support coordination", "Family resource center"],
    tags: ["School", "Santa Ana", "Support services"],
  }),
  resource({
    name: "Anaheim Union High School District Mental Health and Social Services",
    resourceType: "School counselors and school wellness centers",
    city: "Anaheim",
    description: "District student-support page with mental-health and social-service resources for Anaheim-area students and families.",
    websiteUrl: "https://anaheimuhsd.cyberschool.com/District/Department/3859-Student-Support-Services/43010-Mental-Health-Social-Services.html",
    phone: "714-999-3511",
    languages: ["English", "Spanish", "Korean", "Chinese", "Vietnamese", "Other"],
    costTypes: ["Free"],
    ageGroups: ["Youth", "Family"],
    mode: "Hybrid",
    serviceType: "School resources",
    address: "501 N Crescent Way, Anaheim, CA 92801",
    coordinates: { lat: 33.8386003, lng: -117.9484211 },
    locationApproximate: true,
    accessibility: ["District resource page", "Student support services"],
    tags: ["School", "Anaheim", "Social services"],
  }),
  resource({
    name: "Straight Talk Counseling La Mirada",
    resourceType: "Community clinics",
    city: "La Mirada",
    address: "13710 La Mirada Blvd., La Mirada, CA 90638",
    description: "Counseling clinic offering play therapy for children, therapy for teens, family support, support groups, and anxiety/depression help.",
    websiteUrl: "https://www.straighttalkcounseling.org/la-mirada-counseling-services",
    phone: "562-943-0195",
    languages: ["English", "Spanish", "Other"],
    costTypes: ["Sliding Scale", "Insurance Accepted"],
    ageGroups: ["Youth", "Family", "All ages"],
    mode: "Hybrid",
    serviceType: "Counseling centers",
    coordinates: { lat: 33.9063764, lng: -118.011594 },
    accessibility: ["Child, teen, family, and adult counseling", "Support groups available"],
    tags: ["La Mirada", "Teen therapy", "Family counseling"],
  }),
  resource({
    name: "Casa Youth Shelter",
    resourceType: "Teen peer support programs",
    city: "Los Alamitos",
    description: "Emergency temporary shelter, counseling, and support services for youth ages 12-17 who are homeless, abused, runaway, abandoned, or in crisis.",
    websiteUrl: "https://casayouthshelter.org/",
    phone: "800-914-2272",
    languages: ["English", "Spanish", "Other"],
    costTypes: ["Free"],
    ageGroups: ["Youth", "Family"],
    mode: "In-Person",
    serviceType: "Counseling centers",
    address: "10911 Reagan St., Los Alamitos, CA 90720",
    coordinates: { lat: 33.8039366, lng: -118.0697764 },
    locationApproximate: true,
    accessibility: ["Youth shelter for ages 12-17", "Counseling and stabilization support"],
    tags: ["Shelter", "Youth crisis", "Family conflict"],
  }),
  resource({
    name: "Human Options",
    resourceType: "Family support resources",
    city: "Orange County",
    description: "Relationship violence support organization offering crisis hotline support, emergency shelter, counseling, legal advocacy, education, and prevention.",
    websiteUrl: "https://humanoptions.org/",
    phone: "877-854-3594",
    languages: ["English", "Spanish", "Other"],
    costTypes: ["Free", "Sliding Scale"],
    ageGroups: ["Youth", "Family", "All ages"],
    mode: "Hotline",
    serviceType: "Crisis lines",
    address: "CA-45 service area: 11222 Acacia Pkwy, Garden Grove, CA 92840",
    coordinates: { lat: 33.7757294, lng: -117.9368784 },
    locationApproximate: true,
    accessibility: ["24-hour relationship violence hotline", "Safety planning and survivor support"],
    tags: ["Domestic violence", "Safety", "Family support"],
  }),
  resource({
    name: "Laura's House",
    resourceType: "Family support resources",
    city: "Orange County",
    description: "Domestic violence shelter, hotline, counseling, legal advocacy, prevention education, and support services for survivors and children.",
    websiteUrl: "https://laurashouse.org/",
    phone: "866-498-1511",
    languages: ["English", "Spanish", "Other"],
    costTypes: ["Free", "Sliding Scale"],
    ageGroups: ["Youth", "Family", "All ages"],
    mode: "Hotline",
    serviceType: "Crisis lines",
    address: "12453 Lewis St., Suite 201, Garden Grove, CA 92840",
    coordinates: { lat: 33.7836382, lng: -117.8975744 },
    locationApproximate: true,
    accessibility: ["24-hour hotline", "Shelter, therapy, and legal advocacy"],
    tags: ["Domestic violence", "Teen dating violence", "Safety"],
  }),
  resource({
    name: "Interval House",
    resourceType: "Family support resources",
    city: "Orange County",
    description: "Survivor-led domestic violence program serving Los Angeles and Orange Counties with crisis shelters, centers, children's programs, and prevention education.",
    websiteUrl: "https://intervalhouse.org/",
    phone: "714-891-8121",
    languages: ["English", "Vietnamese", "Spanish", "Korean", "Chinese", "Other"],
    costTypes: ["Free"],
    ageGroups: ["Youth", "Family", "All ages"],
    mode: "Hotline",
    serviceType: "Crisis lines",
    address: "CA-45 service area: 11222 Acacia Pkwy, Garden Grove, CA 92840",
    coordinates: { lat: 33.7757294, lng: -117.9368784 },
    locationApproximate: true,
    accessibility: ["Domestic violence support in 70+ languages", "Orange County and Los Angeles County service area"],
    tags: ["Domestic violence", "Multilingual", "Shelter"],
  }),
  resource({
    name: "Radiant Futures",
    resourceType: "Family support resources",
    city: "Fullerton",
    description: "Domestic violence and trafficking support organization providing crisis support, survivor services, housing, counseling, and prevention education.",
    websiteUrl: "https://radiantfutures.org/",
    phone: "877-531-5522",
    languages: ["English", "Vietnamese", "Spanish", "Korean", "Chinese", "Other"],
    costTypes: ["Free", "Sliding Scale"],
    ageGroups: ["Youth", "Family", "All ages"],
    mode: "Hotline",
    serviceType: "Crisis lines",
    address: "201 E Amerige Ave., Fullerton, CA 92832",
    coordinates: { lat: 33.8713201, lng: -117.9219235 },
    locationApproximate: true,
    accessibility: ["24/7 helpline", "Survivor and prevention services"],
    tags: ["Domestic violence", "Trafficking", "Fullerton"],
  }),
  resource({
    name: "Orange County Family Justice Center",
    resourceType: "Family support resources",
    city: "Anaheim",
    description: "Safe, confidential, one-stop support for survivors of domestic violence, child abuse, sexual assault, elder abuse, and dependent adult abuse.",
    websiteUrl: "https://pd.anaheim.net/209/Orange-County-Family-Justice-Center-OCFJ",
    phone: "714-765-1645",
    languages: ["English", "Spanish", "Other"],
    costTypes: ["Free"],
    ageGroups: ["Youth", "Family", "All ages"],
    mode: "In-Person",
    serviceType: "Counseling centers",
    address: "150 W Vermont Ave., Anaheim, CA 92805",
    coordinates: { lat: 33.8227461, lng: -117.9112684 },
    locationApproximate: true,
    accessibility: ["Confidential survivor support", "Court, legal, advocacy, and social-service connections"],
    tags: ["Family violence", "Anaheim", "Victim services"],
  }),
  resource({
    name: "Santa Ana Family Justice Center",
    resourceType: "Family support resources",
    city: "Santa Ana",
    description: "One-stop support center for survivors of domestic violence, sexual assault, child abuse, human trafficking, and elder abuse.",
    websiteUrl: "https://www.santa-ana.org/family-justice-center/",
    phone: "714-245-8278",
    languages: ["English", "Spanish", "Vietnamese", "Other"],
    costTypes: ["Free"],
    ageGroups: ["Youth", "Family", "All ages"],
    mode: "In-Person",
    serviceType: "Counseling centers",
    address: "60 Civic Center Plaza, Santa Ana, CA 92701",
    coordinates: { lat: 33.7511903, lng: -117.8799407 },
    locationApproximate: true,
    accessibility: ["One-stop survivor support", "Partner social-service organizations"],
    tags: ["Family violence", "Santa Ana", "Victim services"],
  }),
  resource({
    name: "KCS Health Center",
    resourceType: "Family support resources",
    city: "Buena Park",
    address: "7212 Orangethorpe Ave., Suite 9A, Buena Park, CA 90621",
    description: "Korean Community Services health center offering culturally responsive health, behavioral-health, social-service, and community programs.",
    websiteUrl: "https://www.kcsinc.org/",
    phone: "714-503-6550",
    languages: ["Korean", "English", "Spanish", "Other"],
    costTypes: ["Sliding Scale", "Insurance Accepted"],
    ageGroups: ["Youth", "Family", "All ages"],
    mode: "Hybrid",
    serviceType: "Bilingual services",
    coordinates: { lat: 33.8582365, lng: -118.007483 },
    accessibility: ["Korean-language support", "Health and social services"],
    tags: ["Korean", "Buena Park", "Culturally responsive"],
  }),
  resource({
    name: "Korean Community Services MECCA",
    resourceType: "Family support resources",
    city: "Orange County",
    description: "Korean Community Services partner in Orange County's multi-ethnic collaborative, providing culturally based behavioral-health and prevention services.",
    websiteUrl: "https://ocmecca.org/collaborative-agencies/korean-community-services/",
    phone: "714-503-6550",
    languages: ["Korean", "English", "Other"],
    costTypes: ["Free", "Sliding Scale"],
    ageGroups: ["Youth", "Family", "All ages"],
    mode: "Hybrid",
    serviceType: "Bilingual services",
    address: "7212 Orangethorpe Ave., Suite 9A, Buena Park, CA 90621",
    coordinates: { lat: 33.8582365, lng: -118.007483 },
    locationApproximate: true,
    accessibility: ["Culturally based behavioral-health collaborative", "Korean-language support"],
    tags: ["Korean", "MECCA", "Behavioral health"],
  }),
  resource({
    name: "211 Orange County",
    resourceType: "Family support resources",
    city: "Orange County",
    description: "Free 24/7 multilingual information and referral service connecting Orange County residents to health, behavioral-health, housing, food, and crisis resources.",
    websiteUrl: "https://211oc.org/",
    phone: "211",
    languages: ["English", "Vietnamese", "Spanish", "Korean", "Chinese", "Japanese", "Other"],
    costTypes: ["Free"],
    ageGroups: ["Youth", "Family", "All ages"],
    mode: "Hotline",
    serviceType: "Crisis lines",
    address: "CA-45 service area: 11222 Acacia Pkwy, Garden Grove, CA 92840",
    coordinates: { lat: 33.7757294, lng: -117.9368784 },
    locationApproximate: true,
    accessibility: ["24/7 multilingual resource navigation", "Dial 2-1-1"],
    tags: ["Navigation", "Multilingual", "Basic needs"],
  }),
  resource({
    name: "CalHOPE Warm Line",
    resourceType: "Teen peer support programs",
    city: "California / CA-45",
    description: "Free emotional support by phone, text, or chat for Californians experiencing stress, anxiety, depression, or difficult life events.",
    websiteUrl: "https://www.calhope.org/",
    phone: "833-317-4673",
    languages: ["English", "Spanish", "Other"],
    costTypes: ["Free"],
    ageGroups: ["Youth", "Family", "All ages"],
    mode: "Hotline",
    serviceType: "Crisis lines",
    address: "CA-45 service area: 11222 Acacia Pkwy, Garden Grove, CA 92840",
    coordinates: { lat: 33.7757294, lng: -117.9368784 },
    locationApproximate: true,
    accessibility: ["Call, text, or live chat", "Peer emotional support"],
    tags: ["Warmline", "California", "Emotional support"],
  }),
  resource({
    name: "OCDE Alcohol and Other Drug Prevention Links",
    resourceType: "Teen peer support programs",
    city: "Orange County",
    description: "Orange County Department of Education prevention links for alcohol and other drug prevention, including ADEPT and youth-serving prevention resources.",
    websiteUrl: "https://ocde.us/OCFNLP/Pages/Alcohol-and-Other-Drug-Prevention-Links.aspx",
    phone: "714-966-4000",
    languages: ["English", "Spanish", "Other"],
    costTypes: ["Free"],
    ageGroups: ["Youth", "Family"],
    mode: "Virtual",
    serviceType: "School resources",
    address: "200 Kalmus Dr., Costa Mesa, CA 92626",
    coordinates: { lat: 33.6731508, lng: -117.8807639 },
    locationApproximate: true,
    accessibility: ["Prevention resource links", "School and family education"],
    tags: ["Substance-use prevention", "OCDE", "Youth"],
  }),
  resource({
    name: "CHHS Youth Mental Health Resources Hub",
    resourceType: "Teen peer support programs",
    city: "California / CA-45",
    description: "California youth mental-health resource hub with digital support options for youth, young adults, and families.",
    websiteUrl: "https://www.chhs.ca.gov/youthresources/",
    phone: "833-317-4673",
    languages: ["English", "Spanish", "Other"],
    costTypes: ["Free"],
    ageGroups: ["Youth", "Family"],
    mode: "Virtual",
    serviceType: "Counseling centers",
    address: "CA-45 service area: 11222 Acacia Pkwy, Garden Grove, CA 92840",
    coordinates: { lat: 33.7757294, lng: -117.9368784 },
    locationApproximate: true,
    accessibility: ["Statewide youth resource hub", "Digital mental-health supports"],
    tags: ["Youth", "Statewide", "Digital support"],
  }),
  resource({
    name: "Orange County Medi-Cal Behavioral Health Provider Directory",
    resourceType: "Orange County Health Care Agency Behavioral Health Services",
    city: "Orange County",
    description: "Official Orange County Behavioral Health Plan provider directory for specialty mental-health services and substance-use disorder providers.",
    websiteUrl: "https://bhpproviderdirectory.ochca.com/",
    phone: "855-625-4657",
    languages: ["English", "Vietnamese", "Spanish", "Korean", "Chinese", "Japanese", "Other"],
    costTypes: ["Insurance Accepted"],
    ageGroups: ["Youth", "Family", "All ages"],
    mode: "Virtual",
    serviceType: "Counseling centers",
    address: "405 W 5th St., Santa Ana, CA 92701",
    coordinates: { lat: 33.7489608, lng: -117.8711732 },
    locationApproximate: true,
    accessibility: ["Medi-Cal behavioral-health provider search", "Specialty mental health and SUD providers"],
    tags: ["Medi-Cal", "Provider directory", "Behavioral health"],
  }),
];

export const cityOptions: CityFilter[] = [
  "All cities",
  ...Array.from(new Set(resources.map((item) => item.city))).sort((a, b) => a.localeCompare(b)),
];
