export type Language = "English" | "Vietnamese" | "Spanish" | "Korean" | "Chinese" | "Japanese" | "Other";
export type CostType = "Free" | "Sliding Scale" | "Insurance Accepted";
export type AgeGroup = "Youth" | "Family" | "All ages";
export type ResourceType =
  | "988 Suicide & Crisis Lifeline"
  | "Orange County Health Care Agency Behavioral Health Services"
  | "CHOC WellSpaces"
  | "School counselors and school wellness centers"
  | "Teen peer support programs"
  | "Community clinics"
  | "Family support resources"
  | "Vietnamese-language mental-health resources";
export type DeliveryMode = "In-Person" | "Virtual" | "Hotline" | "Hybrid";
export type ServiceType = "Counseling centers" | "School resources" | "Crisis lines" | "Community clinics" | "Bilingual services";
export type LanguageFilter = "All languages" | Language;
export type CostFilter = "All costs" | CostType;
export type AgeGroupFilter = "All age groups" | AgeGroup;
export type ResourceTypeFilter = "All resource types" | ResourceType;
export type ServiceTypeFilter = "All service types" | ServiceType;
export type ModeFilter = "Any format" | DeliveryMode;
export type CityFilter = "All cities" | string;

export type Resource = {
  name: string;
  resourceType: ResourceType;
  category: ResourceType;
  city: string;
  description: string;
  websiteUrl: string | null;
  phone: string;
  languages: Language[];
  costTypes: CostType[];
  cost: CostType[];
  ageGroups: AgeGroup[];
  mode: DeliveryMode;
  format: DeliveryMode;
  serviceType: ServiceType;
  coordinates: { lat: number; lng: number };
  accessibility: string[];
  tags: string[];
};

export const languageOptions: LanguageFilter[] = ["All languages", "English", "Vietnamese", "Spanish", "Korean", "Chinese", "Japanese", "Other"];
export const costOptions: CostFilter[] = ["All costs", "Free", "Sliding Scale", "Insurance Accepted"];
export const ageGroupOptions: AgeGroupFilter[] = ["All age groups", "Youth", "Family", "All ages"];
export const resourceTypeOptions: ResourceTypeFilter[] = [
  "All resource types",
  "988 Suicide & Crisis Lifeline",
  "Orange County Health Care Agency Behavioral Health Services",
  "CHOC WellSpaces",
  "School counselors and school wellness centers",
  "Teen peer support programs",
  "Community clinics",
  "Family support resources",
  "Vietnamese-language mental-health resources",
];
export const modeOptions: ModeFilter[] = ["Any format", "In-Person", "Virtual", "Hotline", "Hybrid"];
export const serviceTypeOptions: ServiceTypeFilter[] = [
  "All service types",
  "Counseling centers",
  "School resources",
  "Crisis lines",
  "Community clinics",
  "Bilingual services",
];

const resource = (
  item: Omit<Resource, "category" | "cost" | "format">,
): Resource => ({
  ...item,
  category: item.resourceType,
  cost: item.costTypes,
  format: item.mode,
});

export const resources: Resource[] = [
  resource({
    name: "988 Suicide & Crisis Lifeline",
    resourceType: "988 Suicide & Crisis Lifeline",
    city: "Nationwide / CA-45",
    description: "Immediate 24/7 crisis support for anyone experiencing suicidal thoughts, emotional distress, or concern for someone else.",
    websiteUrl: "https://988lifeline.org/",
    phone: "988",
    languages: ["English", "Vietnamese", "Spanish", "Korean", "Chinese", "Japanese", "Other"],
    costTypes: ["Free"],
    ageGroups: ["All ages"],
    mode: "Hotline",
    serviceType: "Crisis lines",
    coordinates: { lat: 33.7743, lng: -117.9406 },
    accessibility: ["24/7 call, text, and chat", "Interpreter access may be requested"],
    tags: ["Crisis", "Immediate support", "Confidential"],
  }),
  resource({
    name: "OC Links Behavioral Health Navigation",
    resourceType: "Orange County Health Care Agency Behavioral Health Services",
    city: "Orange County",
    description: "Free county behavioral-health navigation that connects residents to mental-health and substance-use referrals, crisis support, and programs.",
    websiteUrl: "https://www.ochealthinfo.com/OCLINKS",
    phone: "855-625-4657",
    languages: ["English", "Vietnamese", "Spanish", "Korean", "Chinese", "Japanese", "Other"],
    costTypes: ["Free"],
    ageGroups: ["Youth", "Family", "All ages"],
    mode: "Hotline",
    serviceType: "Crisis lines",
    coordinates: { lat: 33.7502, lng: -117.8703 },
    accessibility: ["24/7 phone and online chat", "County navigation line"],
    tags: ["Orange County", "Referrals", "Behavioral health"],
  }),
  resource({
    name: "OC HCA Children & Youth Behavioral Health Services",
    resourceType: "Orange County Health Care Agency Behavioral Health Services",
    city: "Orange County",
    description: "County children and youth behavioral-health services, including prevention, crisis recovery, outpatient support, and specialty programs.",
    websiteUrl: "https://www.ochealthinfo.com/services-programs/mental-health-crisis-recovery/children-youth-services",
    phone: "855-625-4657",
    languages: ["English", "Vietnamese", "Spanish", "Korean", "Chinese", "Japanese", "Other"],
    costTypes: ["Free", "Insurance Accepted"],
    ageGroups: ["Youth", "Family"],
    mode: "Hybrid",
    serviceType: "Counseling centers",
    coordinates: { lat: 33.7175, lng: -117.8311 },
    accessibility: ["Countywide youth services", "Call OC Links for navigation"],
    tags: ["Youth", "County services", "Prevention"],
  }),
  resource({
    name: "Be Well OC Orange Campus",
    resourceType: "Orange County Health Care Agency Behavioral Health Services",
    city: "Orange",
    description: "Orange County mental-health and substance-use support campus with system navigation for residents seeking help.",
    websiteUrl: "https://bewelloc.org/be-well-orange-campus/",
    phone: "949-749-2500",
    languages: ["English", "Vietnamese", "Spanish", "Korean", "Chinese", "Japanese", "Other"],
    costTypes: ["Free", "Insurance Accepted"],
    ageGroups: ["All ages"],
    mode: "Hybrid",
    serviceType: "Counseling centers",
    coordinates: { lat: 33.7835, lng: -117.8776 },
    accessibility: ["Non-crisis navigation line", "OC Links for crisis or substance-use support"],
    tags: ["Navigation", "Mental health", "Substance use"],
  }),
  resource({
    name: "NAMI Orange County WarmLine",
    resourceType: "Teen peer support programs",
    city: "Fountain Valley",
    description: "Free confidential emotional support and resource connection for Orange County residents by phone, text, or chat.",
    websiteUrl: "https://www.namioc.org/oc-warmline",
    phone: "714-991-6412",
    languages: ["English", "Spanish", "Korean", "Chinese", "Other"],
    costTypes: ["Free"],
    ageGroups: ["Youth", "Family", "All ages"],
    mode: "Hotline",
    serviceType: "Crisis lines",
    coordinates: { lat: 33.7249, lng: -117.9201 },
    accessibility: ["Call, text, and chat options", "Orange County residents"],
    tags: ["Warmline", "Peer support", "Emotional support"],
  }),
  resource({
    name: "NAMI Orange County Teens & Young Adults",
    resourceType: "Teen peer support programs",
    city: "Fountain Valley",
    description: "Teen and young-adult mental-health resources, peer stories, and support pathways from NAMI Orange County.",
    websiteUrl: "https://www.namioc.org/teens-young-adults",
    phone: "714-544-8488",
    languages: ["English", "Spanish", "Other"],
    costTypes: ["Free"],
    ageGroups: ["Youth"],
    mode: "Hybrid",
    serviceType: "Counseling centers",
    coordinates: { lat: 33.7249, lng: -117.9201 },
    accessibility: ["Youth-focused resources", "Peer and family education"],
    tags: ["Peer support", "Young adults", "Education"],
  }),
  resource({
    name: "NAMI Orange County Family Support Groups",
    resourceType: "Family support resources",
    city: "Fountain Valley",
    description: "Peer-led family support groups and education for caregivers and loved ones supporting someone with a mental-health condition.",
    websiteUrl: "https://www.namioc.org/support-groups",
    phone: "714-544-8488",
    languages: ["English", "Spanish", "Other"],
    costTypes: ["Free"],
    ageGroups: ["Family"],
    mode: "Hybrid",
    serviceType: "Counseling centers",
    coordinates: { lat: 33.7249, lng: -117.9201 },
    accessibility: ["Caregiver-friendly", "Group support options"],
    tags: ["Caregivers", "Family education", "Support groups"],
  }),
  resource({
    name: "Western Youth Services Mental Health Clinics",
    resourceType: "Community clinics",
    city: "Santa Ana",
    description: "Outpatient mental-health services for Orange County children and youth, including Medi-Cal eligible clients under 21.",
    websiteUrl: "https://www.westernyouthservices.org/mental-health-clinics/",
    phone: "888-312-0406",
    languages: ["English", "Spanish", "Other"],
    costTypes: ["Free", "Insurance Accepted"],
    ageGroups: ["Youth", "Family"],
    mode: "Hybrid",
    serviceType: "Counseling centers",
    coordinates: { lat: 33.7476, lng: -117.8677 },
    accessibility: ["Clinic-based and school-based services", "Countywide locations"],
    tags: ["Youth therapy", "Medi-Cal", "Trauma-informed"],
  }),
  resource({
    name: "Waymakers Youth Shelters",
    resourceType: "Teen peer support programs",
    city: "Orange County",
    description: "Short-term shelter and crisis intervention for runaway, homeless, abused, and at-risk youth ages 11-17.",
    websiteUrl: "https://waymakersoc.org/sheltering-children",
    phone: "714-842-6600",
    languages: ["English", "Spanish", "Other"],
    costTypes: ["Free"],
    ageGroups: ["Youth", "Family"],
    mode: "In-Person",
    serviceType: "Counseling centers",
    coordinates: { lat: 33.7459, lng: -117.8265 },
    accessibility: ["24-hour youth shelter hotline", "Youth and family crisis intervention"],
    tags: ["Shelter", "At-risk youth", "Family conflict"],
  }),
  resource({
    name: "The Priority Center",
    resourceType: "Family support resources",
    city: "Santa Ana",
    description: "Early intervention, crisis support, mental-health services, and family advocacy for Orange County children and families.",
    websiteUrl: "https://theprioritycenter.org/programs/",
    phone: "714-543-4333",
    languages: ["English", "Spanish", "Other"],
    costTypes: ["Free", "Sliding Scale"],
    ageGroups: ["Youth", "Family", "All ages"],
    mode: "Hybrid",
    serviceType: "Counseling centers",
    coordinates: { lat: 33.7455, lng: -117.8677 },
    accessibility: ["Family-centered programs", "Crisis and early-intervention support"],
    tags: ["Family support", "Early intervention", "Crisis support"],
  }),
  resource({
    name: "CHOC Pediatric Mental Health Services",
    resourceType: "CHOC WellSpaces",
    city: "Orange",
    description: "Pediatric mental-health resources, education, and behavioral-health information for children, teens, parents, and caregivers.",
    websiteUrl: "https://choc.org/mental-health/",
    phone: "714-997-3000",
    languages: ["English", "Spanish", "Other"],
    costTypes: ["Free", "Insurance Accepted"],
    ageGroups: ["Youth", "Family"],
    mode: "Hybrid",
    serviceType: "Counseling centers",
    coordinates: { lat: 33.7801, lng: -117.8656 },
    accessibility: ["Pediatric focus", "Education resources for families"],
    tags: ["Pediatric", "Mental health education", "Parent support"],
  }),
  resource({
    name: "CHOC WellSpaces",
    resourceType: "CHOC WellSpaces",
    city: "Orange County schools",
    description: "Youth-centered wellness spaces and school-linked supports designed to reduce stress and connect students with trusted adults.",
    websiteUrl: "https://choc.org/population-health/wellspaces/",
    phone: "714-997-3000",
    languages: ["English", "Spanish", "Other"],
    costTypes: ["Free"],
    ageGroups: ["Youth"],
    mode: "In-Person",
    serviceType: "School resources",
    coordinates: { lat: 33.7899, lng: -117.9977 },
    accessibility: ["School-based setting", "Youth-friendly environment"],
    tags: ["CHOC", "Wellness", "School-based"],
  }),
  resource({
    name: "OCAPICA Behavioral Health Services",
    resourceType: "Vietnamese-language mental-health resources",
    city: "Garden Grove",
    description: "Culturally responsive behavioral-health services including therapy, case management, wellness workshops, referrals, and peer support.",
    websiteUrl: "https://www.ocapica.org/bhs.html",
    phone: "714-461-3687",
    languages: ["Vietnamese", "English", "Spanish", "Korean", "Chinese", "Other"],
    costTypes: ["Free", "Sliding Scale"],
    ageGroups: ["Youth", "Family", "All ages"],
    mode: "Hybrid",
    serviceType: "Bilingual services",
    coordinates: { lat: 33.7766, lng: -117.9388 },
    accessibility: ["AAPI-focused services", "Vietnamese and multilingual support"],
    tags: ["Vietnamese", "AAPI", "Case management"],
  }),
  resource({
    name: "Southland Integrated Services Behavioral Health",
    resourceType: "Vietnamese-language mental-health resources",
    city: "Garden Grove",
    description: "Culturally responsive behavioral-health care for Vietnamese Americans and other Orange County communities, including therapy and medication support.",
    websiteUrl: "https://www.southlandintegrated.org/bh.asp",
    phone: "714-620-7000",
    languages: ["Vietnamese", "English", "Spanish", "Chinese", "Other"],
    costTypes: ["Sliding Scale", "Insurance Accepted"],
    ageGroups: ["Youth", "Family", "All ages"],
    mode: "Hybrid",
    serviceType: "Bilingual services",
    coordinates: { lat: 33.7886, lng: -117.9602 },
    accessibility: ["FQHC integrated care", "Vietnamese community roots"],
    tags: ["Vietnamese", "FQHC", "Therapy"],
  }),
  resource({
    name: "Families Together OC Garden Grove Health Center",
    resourceType: "Community clinics",
    city: "Garden Grove",
    description: "Community clinic in Garden Grove offering medical care and mental-health services such as individual counseling.",
    websiteUrl: "https://familiestogetheroc.org/locations/garden-grove",
    phone: "800-597-7977",
    languages: ["English", "Vietnamese", "Spanish", "Korean", "Chinese", "Japanese", "Other"],
    costTypes: ["Sliding Scale", "Insurance Accepted"],
    ageGroups: ["Youth", "Family", "All ages"],
    mode: "Hybrid",
    serviceType: "Community clinics",
    coordinates: { lat: 33.7749, lng: -117.9372 },
    accessibility: ["Community clinic", "Ask about interpretation"],
    tags: ["Clinic", "Counseling", "Garden Grove"],
  }),
  resource({
    name: "Serve the People Behavioral Health",
    resourceType: "Community clinics",
    city: "Santa Ana",
    description: "Affordable behavioral-health care and counseling services from an integrated community health center in Santa Ana.",
    websiteUrl: "https://www.servethepeople.org/behavioral-health",
    phone: "714-352-2911",
    languages: ["English", "Vietnamese", "Spanish", "Korean", "Chinese", "Japanese", "Other"],
    costTypes: ["Sliding Scale", "Insurance Accepted"],
    ageGroups: ["Youth", "Family", "All ages"],
    mode: "Hybrid",
    serviceType: "Community clinics",
    coordinates: { lat: 33.7599, lng: -117.8519 },
    accessibility: ["Affordable community clinic", "Integrated medical and behavioral health"],
    tags: ["Santa Ana", "Counseling", "Clinic"],
  }),
  resource({
    name: "AltaMed Behavioral Health Services",
    resourceType: "Community clinics",
    city: "Orange County",
    description: "Short-term therapy and behavioral-health linkage through AltaMed for patients and families needing mental-health support.",
    websiteUrl: "https://www.altamed.org/behavioral-health-services",
    phone: "855-425-1777",
    languages: ["English", "Vietnamese", "Spanish", "Korean", "Chinese", "Japanese", "Other"],
    costTypes: ["Insurance Accepted", "Sliding Scale"],
    ageGroups: ["Youth", "Family", "All ages"],
    mode: "Hybrid",
    serviceType: "Community clinics",
    coordinates: { lat: 33.7866, lng: -117.8438 },
    accessibility: ["Community health network", "Bilingual Spanish support"],
    tags: ["Behavioral health", "Clinic", "Spanish"],
  }),
  resource({
    name: "Latino Health Access",
    resourceType: "Family support resources",
    city: "Santa Ana",
    description: "Community-based health education, services, and advocacy with culturally and linguistically appropriate programs for Orange County families.",
    websiteUrl: "https://latinohealthaccess.org/programs/",
    phone: "714-542-7792",
    languages: ["English", "Spanish", "Korean", "Chinese", "Japanese"],
    costTypes: ["Free", "Sliding Scale"],
    ageGroups: ["Youth", "Family", "All ages"],
    mode: "Hybrid",
    serviceType: "Bilingual services",
    coordinates: { lat: 33.7488, lng: -117.8678 },
    accessibility: ["Promotores/community model", "Spanish-language support"],
    tags: ["Family support", "Spanish", "Community health"],
  }),
  resource({
    name: "LGBTQ Center OC Therapy",
    resourceType: "Teen peer support programs",
    city: "Santa Ana",
    description: "LGBTQ-affirming therapy, groups, and mental-health support for Orange County community members.",
    websiteUrl: "https://www.lgbtqcenteroc.org/services/therapy/",
    phone: "714-953-5428",
    languages: ["English", "Spanish", "Other"],
    costTypes: ["Sliding Scale"],
    ageGroups: ["Youth", "Family", "All ages"],
    mode: "Hybrid",
    serviceType: "Counseling centers",
    coordinates: { lat: 33.7594, lng: -117.8674 },
    accessibility: ["LGBTQ-affirming care", "Sliding-scale groups"],
    tags: ["LGBTQ", "Therapy", "Santa Ana"],
  }),
  resource({
    name: "California Youth Crisis Line",
    resourceType: "Teen peer support programs",
    city: "California / CA-45",
    description: "24/7 statewide crisis support for youth ages 12-24 and families in crisis, with counseling and local resource referrals.",
    websiteUrl: "https://calyouth.org/cycl/",
    phone: "800-843-5200",
    languages: ["English", "Spanish", "Other"],
    costTypes: ["Free"],
    ageGroups: ["Youth", "Family"],
    mode: "Hotline",
    serviceType: "Crisis lines",
    coordinates: { lat: 33.7743, lng: -117.9356 },
    accessibility: ["24/7 statewide youth line", "Resource referrals"],
    tags: ["Youth crisis", "Hotline", "California"],
  }),
  resource({
    name: "Teen Line by Didi Hirsch",
    resourceType: "Teen peer support programs",
    city: "California / CA-45",
    description: "Peer-to-peer teen support line where trained teens help other teens talk through stress, relationships, anxiety, and crisis concerns.",
    websiteUrl: "https://didihirsch.org/teenline/",
    phone: "800-852-8336",
    languages: ["English", "Spanish", "Other"],
    costTypes: ["Free"],
    ageGroups: ["Youth"],
    mode: "Hotline",
    serviceType: "Crisis lines",
    coordinates: { lat: 33.7713, lng: -117.948 },
    accessibility: ["Teen peer support", "Evening hotline"],
    tags: ["Peer support", "Teen hotline", "Didi Hirsch"],
  }),
  resource({
    name: "The Trevor Project",
    resourceType: "Teen peer support programs",
    city: "Nationwide / CA-45",
    description: "24/7 crisis support and suicide prevention services for LGBTQ+ young people by phone, chat, and text.",
    websiteUrl: "https://www.thetrevorproject.org/",
    phone: "866-488-7386",
    languages: ["English", "Spanish", "Other"],
    costTypes: ["Free"],
    ageGroups: ["Youth"],
    mode: "Hotline",
    serviceType: "Crisis lines",
    coordinates: { lat: 33.7696, lng: -117.9367 },
    accessibility: ["24/7 LGBTQ+ youth crisis support", "Phone, chat, and text"],
    tags: ["LGBTQ", "Crisis", "Youth"],
  }),
  resource({
    name: "Crisis Text Line",
    resourceType: "988 Suicide & Crisis Lifeline",
    city: "Nationwide / CA-45",
    description: "Free 24/7 confidential text-based crisis support with trained volunteer Crisis Counselors.",
    websiteUrl: "https://www.crisistextline.org/",
    phone: "Text HOME to 741741",
    languages: ["English", "Spanish"],
    costTypes: ["Free"],
    ageGroups: ["Youth", "Family", "All ages"],
    mode: "Hotline",
    serviceType: "Crisis lines",
    coordinates: { lat: 33.7793, lng: -117.9468 },
    accessibility: ["Text-based support", "24/7 confidential service"],
    tags: ["Text", "Crisis", "Confidential"],
  }),
  resource({
    name: "GGUSD Mental Health Resources",
    resourceType: "School counselors and school wellness centers",
    city: "Garden Grove",
    description: "Garden Grove Unified mental-health resource page with crisis numbers, district supports, and community resource links for students and families.",
    websiteUrl: "https://ggusd.us/resources/wellness-resources/mental-health-resources",
    phone: "714-663-6000",
    languages: ["English", "Vietnamese", "Spanish", "Other"],
    costTypes: ["Free"],
    ageGroups: ["Youth", "Family"],
    mode: "Hybrid",
    serviceType: "School resources",
    coordinates: { lat: 33.7739, lng: -117.9414 },
    accessibility: ["School district resources", "Ask school site for interpretation"],
    tags: ["School", "Garden Grove", "Wellness"],
  }),
  resource({
    name: "Westminster High School THE WELL",
    resourceType: "School counselors and school wellness centers",
    city: "Westminster",
    description: "On-campus wellness center offering free student mental-health services, family support, case management, and referrals during school hours.",
    websiteUrl: "https://www.whslions.net/apps/pages/index.jsp?type=d&uREC_ID=4352301",
    phone: "714-893-1381",
    languages: ["English", "Vietnamese", "Spanish", "Other"],
    costTypes: ["Free"],
    ageGroups: ["Youth", "Family"],
    mode: "In-Person",
    serviceType: "School resources",
    coordinates: { lat: 33.7616, lng: -117.9935 },
    accessibility: ["For Westminster High students", "On-campus support"],
    tags: ["School wellness", "Westminster", "Student support"],
  }),
  resource({
    name: "HBUHSD Wellness Resources",
    resourceType: "School counselors and school wellness centers",
    city: "Huntington Beach / Fountain Valley / Westminster",
    description: "Huntington Beach Union High School District wellness resources and student mental-health supports, including teletherapy information.",
    websiteUrl: "https://www.hbuhsd.edu/apps/pages/wellness",
    phone: "714-903-7000",
    languages: ["English", "Spanish", "Other"],
    costTypes: ["Free"],
    ageGroups: ["Youth", "Family"],
    mode: "Hybrid",
    serviceType: "School resources",
    coordinates: { lat: 33.7217, lng: -117.9848 },
    accessibility: ["District student resources", "Virtual support information"],
    tags: ["School", "Teletherapy", "Wellness"],
  }),
  resource({
    name: "Fountain Valley School District Mental Health & Wellness Resources",
    resourceType: "School counselors and school wellness centers",
    city: "Fountain Valley",
    description: "District mental-health and wellness resource page with crisis contacts, community partners, and family support links.",
    websiteUrl: "https://www.fvsd.us/apps/pages/MentalHealthAndWellnessResources",
    phone: "714-843-3200",
    languages: ["English", "Spanish", "Other"],
    costTypes: ["Free"],
    ageGroups: ["Youth", "Family"],
    mode: "Hybrid",
    serviceType: "School resources",
    coordinates: { lat: 33.7092, lng: -117.9537 },
    accessibility: ["District resource page", "Family and student supports"],
    tags: ["School", "Fountain Valley", "Wellness"],
  }),
  resource({
    name: "Westminster School District Family/Community Resources",
    resourceType: "School counselors and school wellness centers",
    city: "Westminster",
    description: "Westminster School District family and community resource hub with mental-health, wellness, medical, and support information.",
    websiteUrl: "https://www.wsdk8.us/parentstudent/familycommunity-resources",
    phone: "714-894-7311",
    languages: ["English", "Vietnamese", "Spanish", "Other"],
    costTypes: ["Free"],
    ageGroups: ["Youth", "Family"],
    mode: "Hybrid",
    serviceType: "School resources",
    coordinates: { lat: 33.7592, lng: -117.9931 },
    accessibility: ["School district family resources", "Community support links"],
    tags: ["School", "Westminster", "Family resources"],
  }),
];

export const cityOptions: CityFilter[] = [
  "All cities",
  ...Array.from(new Set(resources.map((item) => item.city))).sort((a, b) => a.localeCompare(b)),
];
